# Generated by Django 6.0.3 on 2026-05-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
