# Generated by Django 6.0.3 on 2026-05-18

from django.conf import settings
from django.db import migrations, models


def assign_period_users(apps, schema_editor):
    Period = apps.get_model("apps", "Period")
    User = apps.get_model("apps", "User")
    Assessment = apps.get_model("apps", "Assessment")
    GradePart = apps.get_model("apps", "GradePart")
    AssessmentTypeWeight = apps.get_model("apps", "AssessmentTypeWeight")
    GradePeriod = apps.get_model("apps", "GradePeriod")

    fallback_user = User.objects.order_by("id").first()
    fallback_user_id = fallback_user.id if fallback_user else None

    for period in Period.objects.filter(user__isnull=True).order_by("id"):
        user_ids = set(
            uid
            for uid in (
                list(
                    Assessment.objects.filter(
                        period_id=period.id,
                        schedule__user_id__isnull=False,
                    ).values_list("schedule__user_id", flat=True)
                )
                + list(
                    GradePart.objects.filter(
                        period_id=period.id,
                        schedule__user_id__isnull=False,
                    ).values_list("schedule__user_id", flat=True)
                )
                + list(
                    AssessmentTypeWeight.objects.filter(
                        period_id=period.id,
                        schedule__user_id__isnull=False,
                    ).values_list("schedule__user_id", flat=True)
                )
                + list(
                    GradePeriod.objects.filter(
                        period_id=period.id,
                        record__schedule__user_id__isnull=False,
                    ).values_list("record__schedule__user_id", flat=True)
                )
            )
            if uid is not None
        )

        if not user_ids:
            if fallback_user_id is not None:
                period.user_id = fallback_user_id
                period.save(update_fields=["user"])
            continue

        sorted_user_ids = sorted(user_ids)
        period.user_id = sorted_user_ids[0]
        period.save(update_fields=["user"])

        for user_id in sorted_user_ids[1:]:
            clone = Period.objects.create(
                user_id=user_id,
                name=period.name,
                position=period.position,
                weight=period.weight,
                is_active=period.is_active,
            )
            Assessment.objects.filter(
                period_id=period.id,
                schedule__user_id=user_id,
            ).update(period_id=clone.id)
            GradePart.objects.filter(
                period_id=period.id,
                schedule__user_id=user_id,
            ).update(period_id=clone.id)
            AssessmentTypeWeight.objects.filter(
                period_id=period.id,
                schedule__user_id=user_id,
            ).update(period_id=clone.id)
            GradePeriod.objects.filter(
                period_id=period.id,
                record__schedule__user_id=user_id,
            ).update(period_id=clone.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_period_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="period",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(assign_period_users, noop_reverse),
    ]
