# Generated by Django 6.0.3 on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_period_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="section",
            name="school_year_sem",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sections",
                to="apps.schoolyearsemester",
            ),
        ),
        migrations.AddField(
            model_name="section",
            name="year_level",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="subject",
            name="code",
            field=models.CharField(default="SUBJ-001", max_length=30),
        ),
        migrations.AddField(
            model_name="subject",
            name="units",
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterUniqueTogether(
            name="section",
            unique_together={("school_year_sem", "name")},
        ),
    ]
