# Generated by Django 6.0.3 on 2026-05-18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_subject_section_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="period",
            name="position",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="period",
            name="time_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="period",
            name="time_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schedule",
            name="day",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="period",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apps.period",
            ),
        ),
    ]
