# Generated by Django 6.0.3 on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0006_student_profile_and_enrollment_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="gradingtemplate",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gradingtemplate",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gradingtemplate",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="gradingtemplateitem",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="gradingtemplateitem",
            name="order",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="schedule",
            name="grading_template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apps.gradingtemplate",
            ),
        ),
        migrations.AlterField(
            model_name="gradingtemplate",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="apps.subject",
            ),
        ),
        migrations.AlterField(
            model_name="gradingtemplateitem",
            name="type",
            field=models.CharField(max_length=60),
        ),
    ]
