# Generated by Django 6.0.3 on 2026-05-19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0007_gradingtemplate_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="component",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="apps.gradingtemplateitem",
            ),
        ),
        migrations.AddField(
            model_name="assessment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="assessment",
            name="type",
            field=models.CharField(max_length=60),
        ),
    ]
